import Head from "next/head";
import ProfileSideBar from "../components/ProfileSideBar";
import Profile from "../components/Profile";
import MenuSideBar from "../components/MenuSideBar";
import Education from "../components/Education";
import Experience from "../components/Experience";
import Projects from "../components/Projects";

export default function Home() {
  return (
    <div className="px-32">
      <Head>
        <title>Faeze Mohrechi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/fm2.png" />
      </Head>

      <main>
        <div className="grid grid-cols-12 gap-14">
          <div className="col-start-1 col-end-4">
            <ProfileSideBar />
          </div>

          <div className="col-start-4 col-end-12">
            <Profile />
            <div className="my-16">
              <Experience />
            </div>
            <div className="my-16">
              <Education />
            </div>
            <div className="my-16">
              <Projects />
            </div>
          </div>

          <div className="col-start-12 col-end-12">
            <MenuSideBar />
          </div>
        </div>
      </main>
    </div>
  );
}
