name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.TOKEN }}

    - name: Install Dependencies
      run: npm install

    - name: Build Project
      run: npm run build

    - name: Show host
      run: echo $SERVER_IP

    - name: Show username
      run: echo $SERVER_USERNAME
      
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: manne.ir
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/ubuntu/mohrechi-portfolio
          git pull origin main
          npm install
          npm run build
          npm start -- --port 8000
